version: 0.2

phases:
    install:
        runtime-versions:
            dotnet: 3.1
    build:
        commands:
          - dotnet build -c Release ApiTestingFramework
          - dotnet test ApiTestingFramework/bin/Release/netcoreapp3.1/ApiTestingFramework.dll --logger trx --results-directory ./testresults
reports:
    DotnetTestExamples:
        file-format: VisualStudioTrx
        files:
            - '**/*'
        base-directory: './testresults'